# Generated by Django 6.0.4 on 2026-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_two_step_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='hr_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='hr_status',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='sd_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='sd_status',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_HEAD', 'Pending Head Approval'), ('PENDING_HR', 'Pending HR Approval'), ('PENDING_SD', 'Pending SD Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_HEAD', max_length=20),
        ),
    ]
